const { app, BrowserWindow } = require('electron');
const fs = require('fs');
const path = require('path');
const assert = require('assert/strict');
fs.mkdirSync(path.resolve('release/debug'), { recursive: true });
app.setPath('userData', fs.mkdtempSync(path.join(app.getPath('temp'), 'mindflow-floating-test-')));
require(path.resolve('electron/apiServer.cjs')).init = () => {};
require(path.resolve('electron/main.cjs'));
const sleep = ms => new Promise(r => setTimeout(r, ms));
async function until(fn) { for(let n=0;n<100;n++){const value=await fn();if(value)return value;await sleep(100);}throw Error('Timed out'); }
const js = (win, code) => win.webContents.executeJavaScript(code, true).catch(error => { throw new Error(code + " :: " + error.message); });
const click = (win, label) => js(win, `(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(label)}||b.getAttribute('aria-label')===${JSON.stringify(label)});if(!b)throw Error('Missing button');b.click()})()`);
app.whenReady().then(async()=>{
 try {
  const main=await until(()=>BrowserWindow.getAllWindows()[0]);
  await until(()=>js(main, `!![...document.querySelectorAll('button')].find(b=>b.textContent==='悬浮窗')`).catch(()=>false));
  await click(main,'悬浮窗');
  let float=await until(()=>BrowserWindow.getAllWindows().find(w=>w!==main));
  await until(()=>js(float, `!!document.querySelector('.float-bottom button:not(:disabled)')`).catch(()=>false));
  assert.equal(float.isAlwaysOnTop(),true);
  assert(Math.abs(float.getContentBounds().width - 300) <= 8);assert(Math.abs(float.getContentBounds().height - 180) <= 8);
  assert.equal(await js(float, `typeof window.require`),'undefined');
  await click(float,'＋ 快速新建');await sleep(200);
  assert(Math.abs(float.getContentBounds().height - 290) <= 8);
  await js(float, `(()=>{const el=document.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'悬浮窗测试任务');el.dispatchEvent(new Event('input',{bubbles:true}))})()`);
  await sleep(100);await click(float,'开始');
  await until(()=>js(float, `document.querySelector('.float-task')?.textContent==='悬浮窗测试任务'`));
  await until(()=>js(float, `document.querySelector('[aria-label="累计用时"]').textContent!=='00:00:00'`));
  assert.match(await js(float, `document.querySelector('[aria-label="累计用时"]').textContent`), /00:00:0[1-9]/);
  assert(Math.abs(float.getContentBounds().height - 180) <= 8);
  main.close();await sleep(200);assert.equal(main.isVisible(),false);assert.equal(main.isDestroyed(),false);
  await click(float,'暂停');await until(()=>js(float, `!![...document.querySelectorAll('button')].find(b=>b.textContent==='继续')`));
  const paused=await js(float, `document.querySelector('[aria-label="累计用时"]').textContent`);await sleep(1200);assert.equal(await js(float, `document.querySelector('[aria-label="累计用时"]').textContent`),paused);
  await click(float,'继续');await until(()=>js(float, `!![...document.querySelectorAll('button')].find(b=>b.textContent==='暂停')`));
  await click(float,'折叠悬浮窗');await sleep(200);assert(Math.abs(float.getContentBounds().height - 44) <= 8);
  await click(float,'展开悬浮窗');await sleep(200);
  await click(float,'结束');await until(()=>js(float, `document.querySelector('.float-task')?.textContent==='现在想做什么？'`));
  const stored=await js(main, `JSON.parse(localStorage.getItem('mindflow_tasks_v7'))`);
  assert.equal(stored.length,1);assert.equal(stored[0].status,'Completed');assert(stored[0].totalDuration>=1);
  float.setPosition(180,140);await sleep(300);float.close();await sleep(300);assert.equal(main.isVisible(),true);
  await click(main,'悬浮窗');float=await until(()=>BrowserWindow.getAllWindows().find(w=>w!==main));
  await until(()=>js(float, `!!document.querySelector('.float-bottom button:not(:disabled)')`).catch(()=>false));
  assert.equal(float.getBounds().x,180);assert.equal(float.getBounds().y,140);
  await click(float,'＋ 快速新建');await sleep(200);
  await js(float, `(()=>{const el=document.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'下一件事情');el.dispatchEvent(new Event('input',{bubbles:true}))})()`);
  await sleep(200);fs.writeFileSync(path.resolve('release/debug/floating-input.png'),(await float.webContents.capturePage()).toPNG());
  await click(float,'待办');await until(()=>js(main, `JSON.parse(localStorage.getItem('mindflow_tasks_v7')).length===2`));
  const waiting=await js(main, `JSON.parse(localStorage.getItem('mindflow_tasks_v7'))[1]`);assert.equal(waiting.status,'Waiting');
  // Exercise switching through the same restricted bridge used by the input form.
  const create = title => js(float, `window.floating.command({type:'create', title:${JSON.stringify(title)}, tagId:'t-work', start:true})`);
  assert.equal((await create('先进行的任务')).ok,true);
  await until(()=>js(float, `document.querySelector('.float-task')?.textContent==='先进行的任务'`));
  assert.equal((await create('切换后的任务')).ok,true);
  await until(()=>js(float, `document.querySelector('.float-task')?.textContent==='切换后的任务'`));
  const switched=await js(main, `({tasks:JSON.parse(localStorage.getItem('mindflow_tasks_v7')),segments:JSON.parse(localStorage.getItem('mindflow_segments_v7'))})`);
  assert.equal(switched.tasks[2].status,'Paused');assert.equal(switched.tasks[3].status,'Running');
  assert.equal(switched.segments.filter(s=>s.endTime===null).length,1);
  await sleep(200);fs.writeFileSync(path.resolve('release/debug/floating-running.png'),(await float.webContents.capturePage()).toPNG());
  await click(float,'折叠悬浮窗');await sleep(200);
  fs.writeFileSync(path.resolve('release/debug/floating-compact.png'),(await float.webContents.capturePage()).toPNG());
  await click(float,'展开悬浮窗');
  const completeCode=`window.floating.command({type:'complete', taskId:${JSON.stringify(switched.tasks[3].id)}})`;
  assert.equal((await js(float,completeCode)).ok,true);
  assert.equal((await js(float,completeCode)).ok,false);
  assert.equal(await js(main, `JSON.parse(localStorage.getItem('mindflow_tasks_v7')).length`),4);
  fs.writeFileSync(path.resolve('release/debug/floating-smoke-result.json'),JSON.stringify({ok:true,checks:['native 300x180 window','always on top','isolated preload','create via UI','live elapsed','hidden main','pause/resume','compact 44px','complete persisted','restore main','remember position','create waiting'],stored},null,2));
  console.log('FLOATING_SMOKE_OK');app.quit();
 }catch(error){console.error(error);fs.writeFileSync(path.resolve('release/debug/floating-smoke-result.json'),JSON.stringify({ok:false,error:error.stack}));app.exit(1);}
});
